ALTER TABLE students
    ADD COLUMN user_id  INT REFERENCES users (id) ON DELETE CASCADE UNIQUE,
    ADD COLUMN username VARCHAR(30) NOT NULL;

ALTER TABLE teachers
    ADD COLUMN user_id  INT REFERENCES users (id) ON DELETE CASCADE UNIQUE,
    ADD COLUMN username VARCHAR(30) NOT NULL;

ALTER TABLE administrators
    ADD COLUMN user_id  INT REFERENCES users (id) ON DELETE CASCADE UNIQUE,
    ADD COLUMN username VARCHAR(30) NOT NULL;